### ISSUE TITLE
Bash/update-idx30.sh -> update all emiten on IDX30.

### ISSUE THREAD

**Issue by jokoput** [idx-repo/idx-tools#1]
- Sepertinya ini perlu dibentuk script update per index jadi gak hanya idx30.
- Script kalo bisa diubah satu script yg bisa update/download csv dengan memberi argumen nama index. 
- Nanti coba dikumpulkan data semua index biar pembenahannya lebih cepet.

**Comment by koharjidan** [comment]
Tolong dibikin ini ya, mumpung udah rilis.
Berikut adalah daftar lengkap anggota IDX30 terbaru:

1. Adaro Energy Indonesia Tbk. (ADRO)
2. Sumber Alfaria Trijaya Tbk. (AMRT)
3. Aneka Tambang Tbk. (ANTM)
4. Bank Jago Tbk. (ARTO)
5. Astra International Tbk. (ASII)
6. Bank Central Asia Tbk. (BBCA)
7. Bank Negara Indonesia (Persero) Tbk. (BBNI)
8. Bank Rakyat Indonesia (Persero) Tbk. (BBRI)
9. Bank Mandiri (Persero) Tbk. (BMRI)
10. Barito Pacific Tbk. (BRPT)
11. Bukalapak.com Tbk. (BUKA)
12. Charoen Pokphand Indonesia Tbk. (CPIN)
13. Elang Mahkota Teknologi Tbk. (EMTK)
14. Surya Esa Perkasa Tbk. (ESSA)
15. GoTo Gojek Tokopedia Tbk. (GOTO)
16. Harum Energy Tbk. (HRUM)
17. Vale Indonesia Tbk. (INCO)
18. Indofood Sukses Makmur Tbk. (INDF)
19. Indo Tambangraya Megah Tbk. (ITMG)
20. Kalbe Farma Tbk (KLBF)
21. Merdeka Copper Gold Tbk. (MDKA)
22. Medco Energi Internasional Tbk. (MEDC)
23. Perusahaan Gas Negara Tbk. (PGAS)
24. Bukit Asam Tbk. (PTBA)
25. Semen Indonesia (Persero) Tbk. (SMGR)
26. Tower Bersama Infrastructure Tbk. (TBIG)
27. Telkom Indonesia (Persero) Tbk. (TLKM)
28. Sarana Menara Nusantara Tbk. (TOWR)
29. United Tractors Tbk. (UNTR)
30. Unilever Indonesia Tbk. (UNVR)

**Comment by karinavega** [comment]
- [x] Update: https://github.com/idx-repo/idx-data/tree/idx/Index
- [x] Change csv separator to '|'

**Comment by karinavega** [comment]
Done
